
package org.coderic.ws.dian.wsdl;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "IWcfDianCustomerServices", targetNamespace = "http://wcf.dian.colombia")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWcfDianCustomerServices {


    /**
     * 
     * @return
     *     returns org.coderic.ws.dian.wsdl.ExchangeEmailResponse
     */
    @WebMethod(operationName = "GetExchangeEmails", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetExchangeEmails")
    @WebResult(name = "GetExchangeEmailsResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetExchangeEmails", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetExchangeEmails")
    @ResponseWrapper(localName = "GetExchangeEmailsResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetExchangeEmailsResponse")
    public ExchangeEmailResponse getExchangeEmails();

    /**
     * 
     * @param trackId
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "GetStatus", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatus")
    @WebResult(name = "GetStatusResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetStatus", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatus")
    @ResponseWrapper(localName = "GetStatusResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatusResponse")
    public DianResponse getStatus(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        String trackId);

    /**
     * 
     * @param trackId
     * @return
     *     returns org.coderic.ws.dian.wsdl.ArrayOfDianResponse
     */
    @WebMethod(operationName = "GetStatusZip", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusZip")
    @WebResult(name = "GetStatusZipResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetStatusZip", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatusZip")
    @ResponseWrapper(localName = "GetStatusZipResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatusZipResponse")
    public ArrayOfDianResponse getStatusZip(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        String trackId);

    /**
     * 
     * @param trackId
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "GetStatusEvent", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetStatusEvent")
    @WebResult(name = "GetStatusEventResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetStatusEvent", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatusEvent")
    @ResponseWrapper(localName = "GetStatusEventResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetStatusEventResponse")
    public DianResponse getStatusEvent(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        String trackId);

    /**
     * 
     * @param contentFile
     * @param fileName
     * @return
     *     returns org.coderic.ws.dian.wsdl.UploadDocumentResponse
     */
    @WebMethod(operationName = "SendBillAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAsync")
    @WebResult(name = "SendBillAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendBillAsync", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillAsync")
    @ResponseWrapper(localName = "SendBillAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillAsyncResponse")
    public UploadDocumentResponse sendBillAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile);

    /**
     * 
     * @param contentFile
     * @param fileName
     * @param testSetId
     * @return
     *     returns org.coderic.ws.dian.wsdl.UploadDocumentResponse
     */
    @WebMethod(operationName = "SendTestSetAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendTestSetAsync")
    @WebResult(name = "SendTestSetAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendTestSetAsync", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendTestSetAsync")
    @ResponseWrapper(localName = "SendTestSetAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendTestSetAsyncResponse")
    public UploadDocumentResponse sendTestSetAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile,
        @WebParam(name = "testSetId", targetNamespace = "http://wcf.dian.colombia")
        String testSetId);

    /**
     * 
     * @param contentFile
     * @param fileName
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "SendBillSync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillSync")
    @WebResult(name = "SendBillSyncResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendBillSync", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillSync")
    @ResponseWrapper(localName = "SendBillSyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillSyncResponse")
    public DianResponse sendBillSync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile);

    /**
     * 
     * @param contentFile
     * @param fileName
     * @return
     *     returns org.coderic.ws.dian.wsdl.UploadDocumentResponse
     */
    @WebMethod(operationName = "SendBillAttachmentAsync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendBillAttachmentAsync")
    @WebResult(name = "SendBillAttachmentAsyncResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendBillAttachmentAsync", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillAttachmentAsync")
    @ResponseWrapper(localName = "SendBillAttachmentAsyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendBillAttachmentAsyncResponse")
    public UploadDocumentResponse sendBillAttachmentAsync(
        @WebParam(name = "fileName", targetNamespace = "http://wcf.dian.colombia")
        String fileName,
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile);

    /**
     * 
     * @param contentFile
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "SendEventUpdateStatus", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendEventUpdateStatus")
    @WebResult(name = "SendEventUpdateStatusResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendEventUpdateStatus", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendEventUpdateStatus")
    @ResponseWrapper(localName = "SendEventUpdateStatusResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendEventUpdateStatusResponse")
    public DianResponse sendEventUpdateStatus(
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile);

    /**
     * 
     * @param contentFile
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "SendNominaSync", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/SendNominaSync")
    @WebResult(name = "SendNominaSyncResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "SendNominaSync", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendNominaSync")
    @ResponseWrapper(localName = "SendNominaSyncResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.SendNominaSyncResponse")
    public DianResponse sendNominaSync(
        @WebParam(name = "contentFile", targetNamespace = "http://wcf.dian.colombia")
        byte[] contentFile);

    /**
     * 
     * @param accountCode
     * @param accountCodeT
     * @param softwareCode
     * @return
     *     returns org.coderic.ws.dian.wsdl.NumberRangeResponseList
     */
    @WebMethod(operationName = "GetNumberingRange", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetNumberingRange")
    @WebResult(name = "GetNumberingRangeResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetNumberingRange", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetNumberingRange")
    @ResponseWrapper(localName = "GetNumberingRangeResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetNumberingRangeResponse")
    public NumberRangeResponseList getNumberingRange(
        @WebParam(name = "accountCode", targetNamespace = "http://wcf.dian.colombia")
        String accountCode,
        @WebParam(name = "accountCodeT", targetNamespace = "http://wcf.dian.colombia")
        String accountCodeT,
        @WebParam(name = "softwareCode", targetNamespace = "http://wcf.dian.colombia")
        String softwareCode);

    /**
     * 
     * @param trackId
     * @return
     *     returns org.coderic.ws.dian.wsdl.EventResponse
     */
    @WebMethod(operationName = "GetXmlByDocumentKey", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetXmlByDocumentKey")
    @WebResult(name = "GetXmlByDocumentKeyResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetXmlByDocumentKey", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetXmlByDocumentKey")
    @ResponseWrapper(localName = "GetXmlByDocumentKeyResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetXmlByDocumentKeyResponse")
    public EventResponse getXmlByDocumentKey(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        String trackId);

    /**
     * 
     * @param contributorCode
     * @param dateNumber
     * @return
     *     returns org.coderic.ws.dian.wsdl.DocIdentifierWithEventsResponse
     */
    @WebMethod(operationName = "GetDocIdentifierWithEvents", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetDocIdentifierWithEvents")
    @WebResult(name = "GetDocIdentifierWithEventsResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetDocIdentifierWithEvents", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetDocIdentifierWithEvents")
    @ResponseWrapper(localName = "GetDocIdentifierWithEventsResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetDocIdentifierWithEventsResponse")
    public DocIdentifierWithEventsResponse getDocIdentifierWithEvents(
        @WebParam(name = "contributorCode", targetNamespace = "http://wcf.dian.colombia")
        String contributorCode,
        @WebParam(name = "dateNumber", targetNamespace = "http://wcf.dian.colombia")
        String dateNumber);

    /**
     * 
     * @param trackId
     * @return
     *     returns org.coderic.ws.dian.wsdl.DianResponse
     */
    @WebMethod(operationName = "GetReferenceNotes", action = "http://wcf.dian.colombia/IWcfDianCustomerServices/GetReferenceNotes")
    @WebResult(name = "GetReferenceNotesResult", targetNamespace = "http://wcf.dian.colombia")
    @RequestWrapper(localName = "GetReferenceNotes", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetReferenceNotes")
    @ResponseWrapper(localName = "GetReferenceNotesResponse", targetNamespace = "http://wcf.dian.colombia", className = "org.coderic.ws.dian.wsdl.GetReferenceNotesResponse")
    public DianResponse getReferenceNotes(
        @WebParam(name = "trackId", targetNamespace = "http://wcf.dian.colombia")
        String trackId);

}
